export function renderConsole(config = {}) {
  const publicConfig = JSON.stringify({ turnstileSitekey: config.turnstileSitekey || "" }).replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow,noarchive">
<meta name="theme-color" content="#07140d">
<title>AMH WT MCP Agent Console</title>
<style>
:root{--ink:#eaf7ee;--muted:#9bb6a5;--dark:#07140d;--panel:#0d2015;--line:#244b33;--green:#6ee7a3;--bad:#ff7b72}
*{box-sizing:border-box}
body{margin:0;background:radial-gradient(circle at 12% 0,#173d28 0,transparent 34%),var(--dark);color:var(--ink);font:14px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif}
.shell{max-width:1280px;margin:auto;padding:18px}.top,.row,.usageLine{display:flex;align-items:center;gap:10px}.top{justify-content:space-between;margin-bottom:16px}
.brand{display:flex;align-items:center;gap:11px;font-weight:950;letter-spacing:.04em}.mark{width:40px;height:40px;border-radius:12px;background:linear-gradient(135deg,var(--green),#14532d);display:grid;place-items:center;color:#04140b}
.status,.badge{padding:5px 9px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:12px}.tabs{display:flex;gap:8px;overflow:auto;padding-bottom:10px}
.tab,.btn{border:1px solid var(--line);border-radius:10px;padding:10px 13px;font-weight:850;cursor:pointer}.tab{white-space:nowrap;color:var(--muted);background:#091b10}.tab.active,.btn{background:var(--green);color:#062013;border-color:var(--green)}
.btn.alt{background:#173d28;color:var(--ink);border-color:var(--line)}.btn.bad{background:#3b1718;color:#ffc7c2;border-color:#6b2a2c}.btn:disabled{opacity:.5;cursor:not-allowed}
.pane{display:none}.pane.active{display:block}.grid{display:grid;grid-template-columns:360px 1fr;gap:14px}.card{background:linear-gradient(180deg,#10291bef,#0b1d12ef);border:1px solid var(--line);border-radius:16px;padding:16px;box-shadow:0 18px 60px #0004}.card h1,.card h2,.card h3{margin:0 0 12px}
.muted{color:var(--muted)}.ok{color:var(--green)}.badtext{color:var(--bad)}label{display:grid;gap:6px;color:var(--muted);font-size:12px;font-weight:800;margin:10px 0}
input,textarea,select{width:100%;border:1px solid var(--line);border-radius:10px;background:#06120b;color:var(--ink);padding:11px;font:inherit}textarea{min-height:96px;resize:vertical}
.list,.tree{display:grid;gap:8px}.item{width:100%;text-align:left;border:1px solid var(--line);background:#08170e;color:var(--ink);border-radius:11px;padding:11px}.job{cursor:pointer}.job:hover{border-color:var(--green)}
.kicker{font-size:11px;text-transform:uppercase;letter-spacing:.1em;color:var(--green);font-weight:900}.branch{border-left:3px solid var(--green);padding:7px 0 7px 12px}
.progress,.meter{height:9px;background:#051008;border:1px solid var(--line);border-radius:999px;overflow:hidden}.progress span,.meter span{display:block;height:100%;background:linear-gradient(90deg,#22c55e,var(--green));transition:width .4s ease}
.progress{margin:9px 0}.handoff{font-size:12px;color:var(--muted)}pre{white-space:pre-wrap;word-break:break-word;background:#050e08;border:1px solid #173d28;border-radius:11px;padding:12px;max-height:60vh;overflow:auto;color:#cde8d5}
.profileName{font-size:17px;font-weight:900;padding:5px 8px;margin:2px 0;background:transparent;border-color:transparent}.profileName:focus{background:#06120b;border-color:var(--green)}
.usageDock{margin-top:14px;position:sticky;bottom:10px;z-index:4}.usageLine{flex-wrap:wrap}.usageLine strong{font-size:16px}.meter{min-width:180px;flex:1}.login{max-width:540px;margin:10vh auto}.hidden{display:none!important}
@media(max-width:800px){.shell{padding:12px}.grid{grid-template-columns:1fr}.top{align-items:flex-start}.row.stack{display:grid}.card{border-radius:13px;padding:13px}}
</style>
</head>
<body><main class="shell">
<div class="top"><div class="brand"><span class="mark">WT</span><span>-/\\-\\ M H // WT · MCP AGENT CONSOLE</span></div><span class="status" id="connection">Locked</span></div>
<section id="login" class="login card"><div class="kicker">Wrangler Craig + SafeTry</div><h1>Open the operator console</h1><p class="muted">The key becomes a short-lived HttpOnly session and is never saved in browser storage.</p><label>Console key<input id="key" type="password" autocomplete="current-password"></label><div id="turnstile"></div><button id="loginBtn" class="btn">Unlock safely</button><p id="loginMsg" class="badtext"></p></section>
<section id="app" class="hidden">
<nav class="tabs" aria-label="Console sections"><button class="tab active" data-tab="jobs">Jobs</button><button class="tab" data-tab="office">Office</button><button class="tab" data-tab="cloudflare">Cloudflare</button><button class="tab" data-tab="templates">Templates</button><button class="tab" data-tab="skills">Skills</button><button class="tab" data-tab="memory">Memory</button><button class="tab" data-tab="revisions">Revisions</button><button class="tab" data-tab="schedules">Schedules</button><button class="tab" data-tab="logs">Logs</button><button class="tab" data-tab="safety">SafeTry</button></nav>
<section class="pane active" data-pane="jobs"><div class="grid"><div class="card"><div class="kicker">Bounded delegation</div><h2>New agent job</h2><label>Friendly agent name (optional)<input id="agentName" maxlength="80" placeholder="Auto-pick or reuse a fitting teammate"></label><label>Template<select id="template"></select></label><label>Objective<textarea id="objective" placeholder="Exact bounded task and desired evidence"></textarea></label><label>Allowed domains<input id="domains" placeholder="example.com, docs.example.com"></label><label>Seed URLs<textarea id="urls" placeholder="One HTTPS URL per line"></textarea></label><label>Expected page text (health watch only)<input id="expectedText" maxlength="200" placeholder="Catches a 200 response serving the wrong page"></label><label>Relevant context only<textarea id="context" placeholder="Optional compact facts; no secrets"></textarea></label><div class="row stack"><label>Auto repeat<select id="scheduled"><option value="no">No</option><option value="yes">Yes</option></select></label><label>Every minutes<input id="every" type="number" min="60" value="60"></label></div><button id="createJob" class="btn">Create job packet</button></div><div class="card"><div class="row"><h2>Job queue</h2><button id="refresh" class="btn alt">Refresh</button></div><div id="jobs" class="list"></div><div id="jobDetail"></div></div></div></section>
<section class="pane" data-pane="office"><div class="grid"><div class="card"><div class="kicker">Main desk</div><h2>Personal assistant + team</h2><p class="muted">Click a name, edit it, and press Enter. The permanent role stays visible and old job history keeps its original name.</p><div id="agentProfiles" class="list"></div></div><div class="card"><h2>Mail acceptance</h2><p class="muted">Loopback proves Cloudflare send, DNS, inbound routing, and Worker receipt. Google Primary requires a connected Gmail seed-mailbox adapter.</p><button id="testAlert" class="btn">Run mail loopback</button><p id="alertTestResult" class="muted"></p></div></div></section>
<section class="pane" data-pane="cloudflare"><div class="grid"><div class="card"><div class="kicker">Official managed MCP</div><h2>Cloudflare connectors</h2><p class="muted">Tap once, approve on Cloudflare, and come back automatically. Each user authorizes their own account; OAuth tokens stay in that user's Durable Object and your owner token is never shared.</p><p id="mcpConnectStatus" class="muted" role="status">Ready to connect.</p><div id="mcpServers" class="list"></div></div><div class="card"><h2>Discovered tools</h2><p class="muted">Tools appear automatically after approval. Connection does not bypass SafeTry: deploys and mutations still require preview, approval, and a public acceptance handshake.</p><div id="mcpTools" class="tree"></div></div></div></section>
<section class="pane" data-pane="templates"><div class="card"><h2>Guided worker templates</h2><div id="templates" class="tree"></div></div></section>
<section class="pane" data-pane="skills"><div class="card"><div class="kicker">Reusable process memory</div><h2>Skill folders</h2><p class="muted">The coordinator selects these automatically and records them in each job packet. Learned edits become reviewable revisions; they never silently replace live instructions.</p><div id="skills" class="tree"></div></div></section>
<section class="pane" data-pane="memory"><div class="grid"><div class="card"><h2>Continuity Keeper</h2><div id="memory"></div></div><div class="card"><h2>Current briefing packet</h2><pre id="briefing"></pre></div></div></section>
<section class="pane" data-pane="revisions"><div class="card"><h2>Candidate revisions</h2><p class="muted">Approval records a candidate; promotion still requires tests and a release.</p><div id="revisions" class="list"></div></div></section>
<section class="pane" data-pane="schedules"><div class="card"><h2>Automatic runs</h2><div id="schedules" class="list"></div></div></section>
<section class="pane" data-pane="logs"><div class="card"><div class="row"><h2>Redacted audit timeline</h2><button id="refreshLogs" class="btn alt">Refresh</button></div><div id="logs" class="list"></div></div></section>
<section class="pane" data-pane="safety"><div class="grid"><div class="card"><h2>SafeTry flow</h2><div id="safetyFlow" class="tree"></div></div><div class="card"><h2>Wrangler Craig resource map</h2><div id="capabilities" class="tree"></div></div></div></section>
<section class="card usageDock"><div id="usageMeter"></div></section>
</section></main>
<script>
const PUBLIC=${publicConfig};
let csrf="",turnstileToken="",data=null,editingName=false,mcpPollToken=0;
const $=id=>document.getElementById(id);
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);if(cls)node.className=cls;return node}
function clear(node){while(node.firstChild)node.removeChild(node.firstChild)}
function branch(title,body){const node=el("div",undefined,"branch");node.append(el("strong",title),el("div",body,"muted"));return node}
function pretty(value){return JSON.stringify(value,null,2)}
async function api(path,options={}){const headers={"content-type":"application/json",...(options.headers||{})};if(csrf&&options.method&&options.method!=="GET")headers["x-csrf-token"]=csrf;const response=await fetch(path,{credentials:"same-origin",...options,headers});const body=await response.json().catch(()=>({error:"Invalid server response"}));if(!response.ok)throw new Error(body.error||("HTTP "+response.status));return body}
function showTab(name){document.querySelectorAll(".tab").forEach(node=>node.classList.toggle("active",node.dataset.tab===name));document.querySelectorAll(".pane").forEach(node=>node.classList.toggle("active",node.dataset.pane===name))}
document.querySelectorAll(".tab").forEach(node=>node.onclick=()=>showTab(node.dataset.tab));
async function refresh(force=false){if(editingName&&!force)return;data=await api("/api/dashboard");render()}
async function enterConsole(output){csrf=output.csrf;$("key").value="";$("login").classList.add("hidden");$("app").classList.remove("hidden");$("connection").textContent="Secure session · "+output.key_window;await refresh(true);const oauth=new URLSearchParams(location.search).get("oauth");if(oauth){setMcpStatus(oauth==="connected"?"Cloudflare approved · discovering tools…":"Cloudflare approval did not finish · tap retry.",oauth==="connected",oauth!=="connected");history.replaceState({},document.title,location.pathname)}}
async function login(){const message=$("loginMsg");message.textContent="";try{await enterConsole(await api("/api/session",{method:"POST",headers:{authorization:"Bearer "+$("key").value},body:JSON.stringify({turnstile_token:turnstileToken})}))}catch(error){message.textContent=error.message}}
async function resumeSession(){try{await enterConsole(await api("/api/session"))}catch(_){}}
$("loginBtn").onclick=login;
const STAGES={job_created:[5,"Packet created","Landing Guide next"],job_enqueued:[8,"Queued","Landing Guide next"],safety_preflight:[12,"Landing Guide","Scan next"],job_started:[16,"Started","Scan next"],crawl_start:[22,"Status scan","Result next"],crawl_complete:[65,"Scan landed","Result next"],primary_started:[45,"Primary worker","Verifier next"],primary_completed:[64,"Primary landed","Verifier next"],verifier_started:[74,"Verifier","Master next"],verifier_completed:[90,"Verifier landed","Master next"],revision_proposed:[94,"Revision filed","Master next"],site_alert:[96,"OUTAGE","Alert next"],site_recovered:[96,"BACK ONLINE","Receipt next"],site_healthy:[96,"Healthy","Receipt next"],job_completed:[100,"Done","Landed"],job_failed:[100,"Failed","Review details"],job_cancelled:[100,"Cancelled","Stopped"]};
function stageFor(job){const events=(data.events||[]).filter(event=>event.job_id===job.id);for(const event of events){if(STAGES[event.kind])return STAGES[event.kind]}if(job.status==="completed")return STAGES.job_completed;if(job.status==="failed")return STAGES.job_failed;if(job.status==="cancelled")return STAGES.job_cancelled;return STAGES.job_created}
function jobCard(job){const stage=stageFor(job),node=el("button",undefined,"item job"),identity=(job.packet.agent_name||"Agent")+" · "+(job.packet.template_title||job.packet.template_id);node.append(el("div",identity,"kicker"),el("strong",job.packet.objective));const track=el("div",undefined,"progress"),fill=el("span");fill.style.width=stage[0]+"%";track.append(fill);node.append(track,el("div",stage[1]+" → "+stage[2]+" · "+stage[0]+"%","handoff"),el("div",job.status+" · "+job.updated_at,"muted"));node.onclick=()=>detailJob(job.id);return node}
function renderJobs(){const box=$("jobs");clear(box);const active=data.jobs.filter(job=>["queued","running"].includes(job.status)),done=data.jobs.filter(job=>!["queued","running"].includes(job.status));for(const [title,items] of [["Agents running",active],["Done",done]]){if(!items.length)continue;box.append(el("h3",title));items.forEach(job=>box.append(jobCard(job)))}if(!data.jobs.length)box.append(el("p","No jobs yet.","muted"))}
async function detailJob(id){const job=await api("/api/jobs/"+encodeURIComponent(id)),box=$("jobDetail");clear(box);box.append(el("h3","Selected job"));const pre=el("pre");pre.textContent=pretty(job);box.append(pre)}
function renderProfiles(){const box=$("agentProfiles");clear(box);for(const profile of data.agent_profiles||[]){const card=el("div",undefined,"item"),name=document.createElement("input");name.className="profileName";name.value=profile.name;name.setAttribute("aria-label","Edit "+profile.role_title+" name");name.onfocus=()=>editingName=true;name.onblur=()=>editingName=false;name.onkeydown=async event=>{if(event.key!=="Enter")return;event.preventDefault();name.disabled=true;try{await api("/api/agents/"+encodeURIComponent(profile.id),{method:"PATCH",body:JSON.stringify({name:name.value})});editingName=false;await refresh(true)}catch(error){alert(error.message)}finally{name.disabled=false}};card.append(name,el("div",profile.role_title+" · "+profile.kind+(profile.system?" · main desk":""),"kicker"),el("div",profile.description||"","muted"));if(!profile.system){const remove=el("button","Remove profile","btn bad");remove.onclick=async()=>{if(!confirm("Remove this display profile? Existing job history stays intact."))return;await api("/api/agents/"+encodeURIComponent(profile.id),{method:"DELETE",body:"{}"});await refresh(true)};card.append(remove)}box.append(card)}}
function setMcpStatus(message,ok=false,bad=false){const node=$("mcpConnectStatus");if(!node)return;node.textContent=message;node.className=ok?"ok":(bad?"badtext":"muted")}
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function pollMcp(id,popup){const token=++mcpPollToken;for(let attempt=0;attempt<45&&token===mcpPollToken;attempt++){await delay(1000);try{const status=await api("/api/cloudflare-mcp/"+encodeURIComponent(id)+"/status");if(status.ready){setMcpStatus("Connected · "+status.tool_count+" tools discovered.",true);try{if(popup&&!popup.closed)popup.close()}catch(_){}await refresh(true);return}if(status.state==="failed"){setMcpStatus("Connection failed · "+(status.error||"tap retry."),false,true);await refresh(true);return}setMcpStatus("Cloudflare approved? Waiting for secure tool discovery · "+status.state+"…")}catch(error){setMcpStatus(error.message,false,true);return}}setMcpStatus("Still waiting for approval. Finish the Cloudflare window or tap retry.",false,true);await refresh(true)}
async function beginMcpConnect(id,restart,button){let popup=null;try{popup=window.open("about:blank","amhCloudflareOAuth","popup,width=620,height=760");if(popup){popup.document.title="Connecting Cloudflare";popup.document.body.textContent="Opening secure Cloudflare authorization…"}}catch(_){}button.disabled=true;setMcpStatus(restart?"Restarting secure Cloudflare authorization…":"Opening secure Cloudflare authorization…");try{if(restart)await api("/api/cloudflare-mcp/"+encodeURIComponent(id),{method:"DELETE",body:"{}"});const result=await api("/api/cloudflare-mcp/"+encodeURIComponent(id)+"/connect",{method:"POST",body:"{}"});if(result.ready||result.state==="ready"){try{if(popup&&!popup.closed)popup.close()}catch(_){}setMcpStatus("Connected · "+(result.tool_count||0)+" tools discovered.",true);await refresh(true);return}if(!result.auth_url)throw new Error("Cloudflare did not return an authorization link");if(popup)popup.location.replace(result.auth_url);else location.assign(result.auth_url);pollMcp(id,popup)}catch(error){try{if(popup&&!popup.closed)popup.close()}catch(_){}setMcpStatus(error.message,false,true);button.disabled=false}}
function renderMcp(){const servers=$("mcpServers"),tools=$("mcpTools"),connected=new Map((data.cloudflare_mcp?.servers||[]).map(server=>[server.id,server]));clear(servers);clear(tools);for(const item of data.catalog.cloudflare_mcp||[]){const server=connected.get(item.id),ready=server?.state==="ready",card=el("div",undefined,"item");card.append(el("div",server?.state||"not connected","kicker"),el("strong",item.name),el("div",item.purpose,"muted"));const button=el("button",ready?"Disconnect":(server?"Retry easy connect":"Connect with Cloudflare"),ready?"btn bad":"btn");button.onclick=async()=>{button.disabled=true;if(ready){try{mcpPollToken++;await api("/api/cloudflare-mcp/"+encodeURIComponent(item.id),{method:"DELETE",body:"{}"});setMcpStatus(item.name+" disconnected.");await refresh(true)}catch(error){setMcpStatus(error.message,false,true)}finally{button.disabled=false}}else await beginMcpConnect(item.id,!!server,button)};card.append(button);servers.append(card)}for(const tool of data.cloudflare_mcp?.tools||[])tools.append(branch(tool.server_id+" · "+tool.name,tool.description||""));if(!(data.cloudflare_mcp?.tools||[]).length)tools.append(el("p","Connect a Cloudflare service and its tools will appear here automatically.","muted"))}
function renderTemplates(){const select=$("template"),box=$("templates");clear(select);clear(box);for(const template of data.catalog.templates){const option=el("option",template.title);option.value=template.id;select.append(option);const calls=template.deterministic?0:(template.verifier?2:1);box.append(branch(template.title,template.purpose+" · "+calls+" AI call"+(calls===1?"":"s")+"/run · tools: "+template.tools.join(", ")))}}
function renderSkills(){const box=$("skills");clear(box);for(const skill of data.catalog.skills||[])box.append(branch(skill.title,skill.purpose+" · "+skill.lane+" · auto: "+skill.automatic_for.join(", ")+" · "+skill.folder))}
function renderMemory(){const box=$("memory");clear(box);for(const [key,value] of Object.entries(data.state.memory))box.append(branch(key.replaceAll("_"," "),Array.isArray(value)?value.join(" · "):value||"—"));$("briefing").textContent=pretty(data.briefing)}
function renderRevisions(){const box=$("revisions");clear(box);for(const revision of data.revisions){const card=el("div",undefined,"item");card.append(el("div",revision.status,"kicker"),el("strong",revision.proposal.title||revision.id));const pre=el("pre");pre.textContent=pretty(revision.proposal);card.append(pre);if(revision.status==="proposed"){const row=el("div",undefined,"row");for(const decision of ["approved","rejected"]){const button=el("button",decision,decision==="approved"?"btn":"btn bad");button.onclick=async()=>{await api("/api/revisions/"+revision.id,{method:"POST",body:JSON.stringify({decision})});await refresh(true)};row.append(button)}card.append(row)}box.append(card)}if(!data.revisions.length)box.append(el("p","No candidate revisions.","muted"))}
function renderSchedules(){const box=$("schedules");clear(box);for(const schedule of data.schedules){const card=el("div",undefined,"item"),calls=schedule.packet.template_id==="site_health"?0:"bounded";card.append(el("strong",(schedule.packet.agent_name||schedule.packet.template_id)+" · every "+schedule.every_minutes+" minutes"),el("div",calls+" AI calls/run · last "+(schedule.last_run_at||"not yet"),"muted"));const button=el("button","Delete schedule","btn bad");button.onclick=async()=>{await api("/api/schedules/"+schedule.id,{method:"DELETE",body:"{}"});await refresh(true)};card.append(button);box.append(card)}if(!data.schedules.length)box.append(el("p","No automatic schedules.","muted"))}
function renderLogs(){const box=$("logs");clear(box);for(const event of data.events){const card=el("div",undefined,"item");card.append(el("div",event.kind,"kicker"),el("strong",event.actor+" · "+event.ts),el("div",pretty(event.data),"muted"));box.append(card)}}
function renderSafety(){const flow=$("safetyFlow"),caps=$("capabilities");clear(flow);clear(caps);data.catalog.safety_flow.forEach((item,index)=>flow.append(branch(String(index+1),item)));data.catalog.capabilities.forEach(item=>caps.append(branch(item.area+" · "+item.lane,item.operations.join(" · "))))}
function renderUsage(){const box=$("usageMeter"),usage=data.usage||{};clear(box);const line=el("div",undefined,"usageLine"),meter=el("div",undefined,"meter"),fill=el("span");fill.style.width=Math.min(100,Math.round(((usage.harness_calls||0)/Math.max(1,usage.harness_call_limit||1))*100))+"%";meter.append(fill);line.append(el("strong","Today: "+(usage.harness_calls||0)+" / "+(usage.harness_call_limit||0)+" AI calls"),meter,el("span",(usage.harness_calls_remaining||0)+" left · "+(usage.model_profile||"free")+" lane","badge"));box.append(line,el("div",(usage.zero_ai_jobs||0)+" zero-AI jobs · resets "+(usage.resets_at_utc||"00:00 UTC")+" · 10,000 provider neurons/day included; exact neurons remain in Workers AI analytics.","muted"))}
function render(){renderJobs();renderProfiles();renderMcp();renderTemplates();renderSkills();renderMemory();renderRevisions();renderSchedules();renderLogs();renderSafety();renderUsage()}
$("createJob").onclick=async()=>{const payload={agent_name:$("agentName").value,template_id:$("template").value,objective:$("objective").value,allowed_domains:$("domains").value.split(",").map(value=>value.trim()).filter(Boolean),urls:$("urls").value.split(/\\r?\\n/).map(value=>value.trim()).filter(Boolean),expected_text:$("expectedText").value,context:$("context").value,schedule:{enabled:$("scheduled").value==="yes",every_minutes:Number($("every").value)}};try{await api("/api/jobs",{method:"POST",body:JSON.stringify(payload)});$("objective").value="";await refresh(true)}catch(error){alert(error.message)}};
$("refresh").onclick=()=>refresh(true);$("refreshLogs").onclick=()=>refresh(true);
async function pollMail(id,expiresAt){const output=$("alertTestResult");try{const test=await api("/api/alerts/test/"+encodeURIComponent(id));if(test.status==="confirmed"){output.textContent="Mail system confirmed · "+test.confirmed_at;output.className="ok";return}if(test.status==="expired"||Date.now()>Date.parse(expiresAt)){output.textContent="EMAIL LAND FAILED · no loopback receipt before timeout";output.className="badtext";return}output.textContent="Waiting for the Worker to catch its own message…";setTimeout(()=>pollMail(id,expiresAt),3000)}catch(error){output.textContent=error.message;output.className="badtext"}}
$("testAlert").onclick=async()=>{const output=$("alertTestResult");output.className="muted";output.textContent="Sending unique loopback message…";try{const test=await api("/api/alerts/test",{method:"POST",body:"{}"});pollMail(test.id,test.expires_at)}catch(error){output.textContent=error.message;output.className="badtext"}};
if(PUBLIC.turnstileSitekey){const script=document.createElement("script");script.src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit";script.async=true;script.onload=()=>turnstile.render("#turnstile",{sitekey:PUBLIC.turnstileSitekey,action:"harness_login",callback:token=>turnstileToken=token,"expired-callback":()=>turnstileToken=""});document.head.append(script)}
addEventListener("message",event=>{if(event.origin!==location.origin||event.data?.type!=="amh-mcp-oauth")return;setMcpStatus(event.data.ok?"Cloudflare approved · discovering tools…":"Cloudflare approval did not finish · tap retry.",event.data.ok,!event.data.ok)});
resumeSession();
setInterval(()=>{if(!editingName&&!document.hidden&&!$("app").classList.contains("hidden"))refresh().catch(()=>{})},3000);
</script>
</body></html>`;
}
